#pragma once

#include "mperror.h"
#include "cell.h"
#include "atom.h"
#include "algo.h"

namespace molcpp
{

    //! Iterates over particles in a cell generated by CellList
    /*! The link-cell structure is not trivial to iterate over. This helper class
    *  makes that easier both in C++ and provides a Python compatible interface
    *  for direct usage there. An IteratorLinkCell is given the bare essentials
    *  it needs to iterate over a given cell, the cell list, the number of
    *  particles, number of cells and the cell to iterate over. Call next() to
    *  get the index of the next particle in the cell, atEnd() will return true
    *  if you are at the end. In C++, next() will crash the code if you attempt
    *  to iterate past the end (no bounds checking for performance). When called
    *  from Python, a different version of next() is used that will throw
    *  StopIteration at the end.
    *
    *  A loop over all of the particles in a cell can be accomplished with the
    *   following code in C++.
    * \code
    * LinkCell::IteratorLinkCell it = lc.itercell(cell);
    * for (unsigned int i = it.next(); !it.atEnd(); i=it.next())
    *     {
    *     // do something with particle i
    *     }
    * \endcode
    *
    * \note Behavior is undefined if an IteratorLinkCell is accessed after the
    * parent LinkCell is destroyed.
    */
    class AtomInCellIterator
    {

    };

    class CellList
    {

        using cellListArray = std::vector<std::vector<std::vector<std::vector<Atom *>>>>;

    public:
        /**
         * @brief Construct a new Cell List:: Cell List object
         *
         * @param cell
         * @param cell_width Width of cells. If not provided, LinkCell will estimate a cell width based on the number of points and the box size, assuming a constant density of points in the box.
         */
        CellList(Cell *cell, double cell_width = 0);

        std::vector<size_t> compute_cell_count(Cell *cell, double cell_width);

        size_t get_cell_index(Vector3D cell_coords) const;

        void reset(size_t, size_t, size_t);

        void reset();

        void add_atom(Atom *);

        void add_atoms(AtomVec);

        size_t get_ncells();

        size_t get_ncell_x();

        size_t get_ncell_y();

        size_t get_ncell_z();

        double get_cell_width() const;

        AtomInCellIterator get_atoms() const;

        const std::vector<size_t> get_cell_neighbors() const;

        void build();



    private:
        Cell *_cell;
        size_t _ncell_x, _ncell_y, _ncell_z;
        double _cell_width;
        cellListArray _cellListArray;
    };

    std::unique_ptr<CellList> create_cellList(Cell *cell, double cell_width);
}